#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noodles.AspMvc.Helpers
{
    using System;
    
    #line 2 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 3 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 4 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 11 "..\..\Helpers\NoodlesHelper.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.AspMvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.AspMvc.Helpers;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.AspMvc.Helpers.Icons;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public static class NoodlesHelper
    {

public static System.Web.WebPages.HelperResult NodeMethodsDropdown(object obj)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 14 "..\..\Helpers\NoodlesHelper.cshtml"
  
#line default
#line hidden


#line 14 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodsDropdown(obj, null));

#line default
#line hidden


#line 14 "..\..\Helpers\NoodlesHelper.cshtml"
                                  
#line default
#line hidden

});

                                  }


public static System.Web.WebPages.HelperResult NodeMethodsDropdown(object obj, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 16 "..\..\Helpers\NoodlesHelper.cshtml"
  
#line default
#line hidden


#line 16 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodsDropdown(obj, null, null));

#line default
#line hidden


#line 16 "..\..\Helpers\NoodlesHelper.cshtml"
                                        
#line default
#line hidden

});

                                        }


public static System.Web.WebPages.HelperResult NodeMethodsDropdown(object obj, string additionalClasses, string excludedMethodNamesCsv)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 18 "..\..\Helpers\NoodlesHelper.cshtml"
 
    var excludedMethodNames = (excludedMethodNamesCsv ?? "").Split(',');
    var filteredNodeMethods = obj.NodeMethods().Where(nm => excludedMethodNames.Contains(nm.Name) == false);
    if (filteredNodeMethods.Any())
    {
    
#line default
#line hidden


#line 23 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BootstrapHelper.DropdownLinksButton("Actions",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\r\n");



#line 25 "..\..\Helpers\NoodlesHelper.cshtml"
     foreach (var method in filteredNodeMethods)
    {
        
#line default
#line hidden


#line 27 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_template_writer, NodeMethodLink(method));

#line default
#line hidden


#line 27 "..\..\Helpers\NoodlesHelper.cshtml"
                               
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "    ");



#line 29 "..\..\Helpers\NoodlesHelper.cshtml"
         }), additionalClasses));

#line default
#line hidden


#line 29 "..\..\Helpers\NoodlesHelper.cshtml"
                               
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodsMenuLink(object obj)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 33 "..\..\Helpers\NoodlesHelper.cshtml"
  
#line default
#line hidden


#line 33 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodsMenuLink(obj, null));

#line default
#line hidden


#line 33 "..\..\Helpers\NoodlesHelper.cshtml"
                                  
#line default
#line hidden

});

                                  }


public static System.Web.WebPages.HelperResult NodeMethodsMenuLink(object obj, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
  
#line default
#line hidden


#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodsMenuLink(obj, additionalClasses, null));

#line default
#line hidden


#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
                                                     
#line default
#line hidden

});

                                                     }


public static System.Web.WebPages.HelperResult NodeMethodsMenuLink(object obj, string additionalClasses, string excludedMethodNamesCsv)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 37 "..\..\Helpers\NoodlesHelper.cshtml"
 
    var excludedMethodNames = (excludedMethodNamesCsv ?? "").Split(',');
    var nodeMethods = obj.NodeMethods();
    if (nodeMethods.Any(nm => excludedMethodNames.Contains(nm.Name) == false))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"nodeMethodsMenuLink ");



#line 42 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"");



#line 42 "..\..\Helpers\NoodlesHelper.cshtml"
                         WebViewPage.WriteTo(@__razor_helper_writer, nodeMethods.Url());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodeid=\"");



#line 42 "..\..\Helpers\NoodlesHelper.cshtml"
                                                          WebViewPage.WriteTo(@__razor_helper_writer, obj.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-excluded-methods=\"");



#line 42 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                            WebViewPage.WriteTo(@__razor_helper_writer, excludedMethodNamesCsv);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">Actions</a>\r\n");



#line 43 "..\..\Helpers\NoodlesHelper.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodLink(IInvokeable method)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 46 "..\..\Helpers\NoodlesHelper.cshtml"
  
#line default
#line hidden


#line 46 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodLink(method, null));

#line default
#line hidden


#line 46 "..\..\Helpers\NoodlesHelper.cshtml"
                               
#line default
#line hidden

});

                               }


public static System.Web.WebPages.HelperResult NodeMethodLink(IInvokeable method, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 48 "..\..\Helpers\NoodlesHelper.cshtml"
 
    
#line default
#line hidden


#line 49 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodLink(method, additionalClasses,item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");



#line 49 "..\..\Helpers\NoodlesHelper.cshtml"
         WebViewPage.WriteTo(@__razor_template_writer, method.DisplayName);

#line default
#line hidden



#line 49 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                              })));

#line default
#line hidden


#line 49 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Icon(IInvokeable nm)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 52 "..\..\Helpers\NoodlesHelper.cshtml"
 
    var att = nm.GetAttribute<IconAttribute>();
    if (att != null)
    {
        var joinedParts = "icon-" + string.Join(" icon-", att.Parts);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <i class=\"");



#line 57 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, joinedParts);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i>\r\n");



#line 58 "..\..\Helpers\NoodlesHelper.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodIconLink(IInvokeable method, string additionalClasses, string iconName)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 61 "..\..\Helpers\NoodlesHelper.cshtml"
 
    
#line default
#line hidden


#line 62 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodLink(method, "",item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");

WebViewPage.WriteLiteralTo(@__razor_template_writer, "<i class=\"icon-");



#line 62 "..\..\Helpers\NoodlesHelper.cshtml"
   WebViewPage.WriteTo(@__razor_template_writer, iconName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\"></i>");



#line 62 "..\..\Helpers\NoodlesHelper.cshtml"
                                                             })));

#line default
#line hidden


#line 62 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodLink(IInvokeable method, string additionalClasses, Func<dynamic, HelperResult> innerHtml)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 65 "..\..\Helpers\NoodlesHelper.cshtml"
 
    if (method != null)
    {
        var nodeClass = method.AutoSubmit ? "nodeMethodAutoSubmit" : "nodeMethodLink";

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"");



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, nodeClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
            WebViewPage.WriteTo(@__razor_helper_writer, method.Target.NodeType().Name.ToClassName());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "-");



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
                                                           WebViewPage.WriteTo(@__razor_helper_writer, method.Name.ToClassName());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodeid=\"");



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                     WebViewPage.WriteTo(@__razor_helper_writer, method.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"");



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                                         WebViewPage.WriteTo(@__razor_helper_writer, method.Url());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                                                        WebViewPage.WriteTo(@__razor_helper_writer, Icon(method));

#line default
#line hidden



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                                                                     WebViewPage.WriteTo(@__razor_helper_writer, innerHtml(null));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 70 "..\..\Helpers\NoodlesHelper.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodForm(System.Web.Mvc.HtmlHelper html, IInvokeable method, string formClass)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 73 "..\..\Helpers\NoodlesHelper.cshtml"
 
    if (method != null)
    {
    
#line default
#line hidden


#line 76 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Partial("Noodles/NodeMethod", method, new ViewDataDictionary { { "FormClass", formClass ?? "" } }));

#line default
#line hidden


#line 76 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                            
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodForm(System.Web.Mvc.HtmlHelper html, IInvokeable method, string formClass, ViewDataDictionary dict)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 80 "..\..\Helpers\NoodlesHelper.cshtml"
 
    if (method != null)
    {
        dict = dict ?? new ViewDataDictionary();
        dict["FormClass"] = formClass;
    
#line default
#line hidden


#line 85 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodForm(html, method, dict));

#line default
#line hidden


#line 85 "..\..\Helpers\NoodlesHelper.cshtml"
                                       
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodForm(System.Web.Mvc.HtmlHelper html, IInvokeable method, ViewDataDictionary dict)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 89 "..\..\Helpers\NoodlesHelper.cshtml"
 
    if (method != null)
    {
        dict = dict ?? new ViewDataDictionary();

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"nodeMethod\">\r\n        ");



#line 94 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Partial("Noodles/NodeMethod", method, dict));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    </div>\r\n");



#line 96 "..\..\Helpers\NoodlesHelper.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodFormInline(System.Web.Mvc.HtmlHelper html, NodeMethod method)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 99 "..\..\Helpers\NoodlesHelper.cshtml"
 
    if (method != null)
    {
    
#line default
#line hidden


#line 102 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodFormInline(html, method, new ViewDataDictionary()));

#line default
#line hidden


#line 102 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                 
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodFormInline(System.Web.Mvc.HtmlHelper html, NodeMethod method, ViewDataDictionary viewData)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 106 "..\..\Helpers\NoodlesHelper.cshtml"
 
    if (method != null)
    {
        viewData = viewData ?? new ViewDataDictionary();
        viewData.Add("Inline", true);
    
#line default
#line hidden


#line 111 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodForm(html, method, "form-inline", viewData));

#line default
#line hidden


#line 111 "..\..\Helpers\NoodlesHelper.cshtml"
                                                          
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Property(System.Web.Mvc.HtmlHelper Html, NodeProperty property)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 116 "..\..\Helpers\NoodlesHelper.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div data-node-property=\"");



#line 117 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, property.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 118 "..\..\Helpers\NoodlesHelper.cshtml"
          
            
            var propertyVm = property.ToPropertyVm(Html);

            propertyVm.Readonly = true;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div data-node-getter=\"");



#line 123 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, property.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n                <div class=\"control-group\">\r\n                    <label class" +
"=\"control-label\">");



#line 125 "..\..\Helpers\NoodlesHelper.cshtml"
      WebViewPage.WriteTo(@__razor_helper_writer, property.DisplayName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label>\r\n                    <div class=\"controls\">\r\n\r\n");



#line 128 "..\..\Helpers\NoodlesHelper.cshtml"
                          
                            var att = property.CustomAttributes.OfType<ShowAttribute>().SingleOrDefault();
                            if (att != null && !string.IsNullOrWhiteSpace(att.UiHint))
                            {
                                
#line default
#line hidden


#line 132 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Html.BestPartial(property.Value, property.Value == null ? property.PropertyType : property.Value.GetType(), att.UiHint + "."));

#line default
#line hidden


#line 132 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                                                                              
                            }
                            else
                            {
                            
#line default
#line hidden


#line 136 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Html.BestProperty(property.ToPropertyVm(Html).Then(p => p.Readonly = true)));

#line default
#line hidden


#line 136 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                        
                            }
                        

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                    </div>\r\n                </div>\r\n");



#line 142 "..\..\Helpers\NoodlesHelper.cshtml"
                 if (!property.Readonly)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <a class=\"show-setter\" href=\"#edit ");



#line 144 "..\..\Helpers\NoodlesHelper.cshtml"
            WebViewPage.WriteTo(@__razor_helper_writer, property.DisplayName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"><i class=\"icon-edit \"></i></a>\r\n");



#line 145 "..\..\Helpers\NoodlesHelper.cshtml"
                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </div>\r\n");



#line 147 "..\..\Helpers\NoodlesHelper.cshtml"
            if (!property.Readonly)
            {
                

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div data-node-setter=\"");



#line 150 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, property.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n                ");



#line 151 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Html.Partial("Noodles/NodeMethod", property));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                <button class=\"btn btn-inverse hide-setter\">Cancel</button>\r\n  " +
"          </div>\r\n");



#line 154 "..\..\Helpers\NoodlesHelper.cshtml"
            }
        

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </div>\r\n");



#line 157 "..\..\Helpers\NoodlesHelper.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
