#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noodles.AspMvc.Helpers
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.ComponentModel;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 3 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 4 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.AspMvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.AspMvc.Helpers;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.AspMvc.UiAttributes;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class NoodlesHelper
    {

public static System.Web.WebPages.HelperResult NodeLink(HtmlHelper html, INode node)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 12 "..\..\Helpers\NoodlesHelper.cshtml"
  
#line default
#line hidden


#line 12 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeLink(html, node, null));

#line default
#line hidden


#line 12 "..\..\Helpers\NoodlesHelper.cshtml"
                             
#line default
#line hidden

});

                             }


public static System.Web.WebPages.HelperResult NodeLink(HtmlHelper html, INode node, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 14 "..\..\Helpers\NoodlesHelper.cshtml"
 
    
#line default
#line hidden


#line 15 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeLink(html, node, additionalClasses,item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");



#line 15 "..\..\Helpers\NoodlesHelper.cshtml"
       WebViewPage.WriteTo(@__razor_template_writer, node.DisplayName);

#line default
#line hidden



#line 15 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                          })));

#line default
#line hidden


#line 15 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                             

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeLink(HtmlHelper html, INode node, string additionalClasses, Func<dynamic, HelperResult> innerHtml)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 18 "..\..\Helpers\NoodlesHelper.cshtml"
 
    if (node != null)
    {
        var viewAtt = node.Attributes.OfType<IRenderHtml>().SingleOrDefault();

        if (viewAtt != null)
        {
            
#line default
#line hidden


#line 25 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, viewAtt.Render(html, node,item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");

WebViewPage.WriteLiteralTo(@__razor_template_writer, "<a class=\"node-link ");



#line 25 "..\..\Helpers\NoodlesHelper.cshtml"
                 WebViewPage.WriteTo(@__razor_template_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");



#line 25 "..\..\Helpers\NoodlesHelper.cshtml"
                                            WebViewPage.WriteTo(@__razor_template_writer, node.DisplayName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\" href=\"");



#line 25 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                      WebViewPage.WriteTo(@__razor_template_writer, node.Url);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\">");



#line 25 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                 WebViewPage.WriteTo(@__razor_template_writer, innerHtml(null));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "</a>");



#line 25 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                                                                })));

#line default
#line hidden


#line 25 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                                                                   
        }
        else
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <a class=\"node-link ");



#line 29 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"");



#line 29 "..\..\Helpers\NoodlesHelper.cshtml"
                       WebViewPage.WriteTo(@__razor_helper_writer, node.Url);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 29 "..\..\Helpers\NoodlesHelper.cshtml"
                                  WebViewPage.WriteTo(@__razor_helper_writer, innerHtml(null));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 30 "..\..\Helpers\NoodlesHelper.cshtml"
        }
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodLink(IInvokeable method)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
  
#line default
#line hidden


#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodLink(method, null));

#line default
#line hidden


#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
                               
#line default
#line hidden

});

                               }


public static System.Web.WebPages.HelperResult NodeMethodLink(IInvokeable method, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 37 "..\..\Helpers\NoodlesHelper.cshtml"
 
    
#line default
#line hidden


#line 38 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodLink(method, additionalClasses,item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");



#line 38 "..\..\Helpers\NoodlesHelper.cshtml"
         WebViewPage.WriteTo(@__razor_template_writer, method.InvokeDisplayName);

#line default
#line hidden



#line 38 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                    })));

#line default
#line hidden


#line 38 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                       

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodLink(IInvokeable method, string additionalClasses, Func<dynamic, HelperResult> innerHtml)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 41 "..\..\Helpers\NoodlesHelper.cshtml"
 
    if (method != null)
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"nodeMethodLink ");



#line 44 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 44 "..\..\Helpers\NoodlesHelper.cshtml"
              WebViewPage.WriteTo(@__razor_helper_writer, method.Target.NodeType().Name.ToClassName());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"");



#line 44 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                   WebViewPage.WriteTo(@__razor_helper_writer, method.InvokeUrl);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 44 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                      WebViewPage.WriteTo(@__razor_helper_writer, innerHtml(null));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 45 "..\..\Helpers\NoodlesHelper.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Form(HtmlHelper html, INode node)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 49 "..\..\Helpers\NoodlesHelper.cshtml"
 
    var settableProperties = ((IInvokeable)node).Parameters.Where(p => p.Readonly == false);
    
#line default
#line hidden


#line 51 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Form(html, node, settableProperties));

#line default
#line hidden


#line 51 "..\..\Helpers\NoodlesHelper.cshtml"
                                         

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Form(HtmlHelper html, INode node, IEnumerable<IInvokeableParameter> fieldsToDisplay)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 55 "..\..\Helpers\NoodlesHelper.cshtml"
 

    var isNodeMethod = node is NodeMethod;
    var fields = fieldsToDisplay as IInvokeableParameter[] ?? fieldsToDisplay.ToArray();
    if (isNodeMethod || fields.Any())
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <form class=\"node-form\" action=\"");



#line 61 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, node.Url);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" method=\"POST\">\r\n");



#line 62 "..\..\Helpers\NoodlesHelper.cshtml"
          
        var descriptionAttribute = node.Attributes.OfType<DescriptionAttribute>().SingleOrDefault();
        if (descriptionAttribute != null)
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div class=\"noodles-callout noodles-callout-info\">\r\n                ");



#line 67 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Raw(descriptionAttribute.Description));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n            </div>\r\n");



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
        }
        

#line default
#line hidden



#line 71 "..\..\Helpers\NoodlesHelper.cshtml"
         if (html.ViewData.ModelState.SelectMany(ms => ms.Value.Errors).Any())
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div class=\"noodles-callout noodles-callout-danger\">\r\n               " +
" Please correct the issues below: ");



#line 74 "..\..\Helpers\NoodlesHelper.cshtml"
      WebViewPage.WriteTo(@__razor_helper_writer, html.ValidationSummary(true));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n            </div>\r\n");



#line 76 "..\..\Helpers\NoodlesHelper.cshtml"
        }

#line default
#line hidden



#line 77 "..\..\Helpers\NoodlesHelper.cshtml"
         foreach (var field in fields)
        {
            var parameter = field;
            var vm = parameter.ToPropertyVm();
            
#line default
#line hidden


#line 81 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Partial("FormFactory/Form.Property", vm));

#line default
#line hidden


#line 81 "..\..\Helpers\NoodlesHelper.cshtml"
                                                          
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <input type=\"submit\" value=\"");



#line 83 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, isNodeMethod ? node.DisplayName : "Update");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n    </form>\r\n");



#line 85 "..\..\Helpers\NoodlesHelper.cshtml"

    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult DropdownNode(HtmlHelper Html, INode node, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 90 "..\..\Helpers\NoodlesHelper.cshtml"
 
    
#line default
#line hidden


#line 91 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BootstrapHelper.DropdownLinksButton(node.DisplayName,item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");

WebViewPage.WriteLiteralTo(@__razor_template_writer, "<li style=\"margin: 20px; width: 400px;\" class=\"keep-open\">\r\n                     " +
"                                           ");



#line 92 "..\..\Helpers\NoodlesHelper.cshtml"
                   WebViewPage.WriteTo(@__razor_template_writer, NoodlesHelper.Form(Html, node));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\r\n                                                            </li>");



#line 93 "..\..\Helpers\NoodlesHelper.cshtml"
                                                               }), additionalClasses));

#line default
#line hidden


#line 93 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                     

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Property(HtmlHelper html, NodeProperty property)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 97 "..\..\Helpers\NoodlesHelper.cshtml"
 
    var vm = property.ToPropertyVm();
    vm.Readonly = true;
    html.RenderPartial("FormFactory/Form.Property", vm);

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
