#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoodle.Example.Views.Shared.WebNoodle
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
    using Microsoft.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
    using WebNoodle;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/WebNoodle/NodeActionForm.cshtml")]
    public class NodeActionForm : System.Web.Mvc.WebViewPage<global::WebNoodle.Reflection.IObjectMethod>
    {
        public NodeActionForm()
        {
        }
        public override void Execute()
        {





WriteLiteral("<form action=\"");


            
            #line 6 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
         Write(Model.Target.Path());

            
            #line default
            #line hidden
WriteLiteral("?action=");


            
            #line 6 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
                                     Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" method=\"post\" enctype=\"multipart/form-data\" encoding=\"multipart/form-data\">\r\n");


            
            #line 7 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
 if (Context.Request.IsAjaxRequest())
{
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
                            
}

            
            #line default
            #line hidden
WriteLiteral("    \r\n<div class=\"modal-header\">\r\n    <a href=\"#\" class=\"close\">×</a>\r\n    <h3>");


            
            #line 14 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
   Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n</div>\r\n<div class=\"modal-body\">\r\n");


            
            #line 17 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
     foreach (var parameter in Model.Parameters)
    {
        var vm = new PropertyVm(Html, parameter.ParameterType, parameter.Name, parameter.Id(), parameter.DisplayName)
        {
            GetCustomAttributes = () => new Attribute[] { },
            IsWritable = true,
            Value = parameter.Value,
            Choices = parameter.Choices,
            Suggestions = parameter.Suggestions

        };

        Html.RenderPartial("FormFactory/Form.Property", vm);

    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div class=\"modal-footer\">\r\n    <input type=\"submit\" class=\"btn primary p" +
"ost-via-ajax\" value=\"");


            
            #line 34 "..\..\Views\Shared\WebNoodle\NodeActionForm.cshtml"
                                                             Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n</div>\r\n</form>\r\n");


        }
    }
}
#pragma warning restore 1591
