#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoodle.Views.Shared.WebNoodle
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
    using WebNoodle;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
    using WebNoodle.Helpers;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
    using WebNoodle.Reflection;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    public static class Helpers
    {

public static System.Web.WebPages.HelperResult NodeActionsDropdown(object obj)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
     
    
#line default
#line hidden


#line 7 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeActionsDropdown(obj, null));

#line default
#line hidden


#line 7 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                   

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionsDropdown(object obj, string additionalClasses)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 10 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
     
    if (obj.NodeMethods().Any())
    {
    
#line default
#line hidden


#line 13 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Bootstrap.DropdownLinksButton("Actions",item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\r\n");



#line 14 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
     foreach (var method in obj.NodeMethods())
    {
        
#line default
#line hidden


#line 16 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_template_writer, NodeActionsLink(method));

#line default
#line hidden


#line 16 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "    ");



#line 18 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
         })));

#line default
#line hidden


#line 18 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
            
    }
    

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionsLink(object obj){
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 22 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                     
#line default
#line hidden


#line 22 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeActionsLink(obj, null));

#line default
#line hidden


#line 22 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                                                
#line default
#line hidden

});

                                                                }


public static System.Web.WebPages.HelperResult NodeActionsLink(object obj, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 24 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <a class=\"nodeActionsLink ");



#line 25 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"#action-");



#line 25 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                 WebViewPage.WriteTo(@__razor_helper_writer, obj.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodeid=\"");



#line 25 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                                         WebViewPage.WriteTo(@__razor_helper_writer, obj.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodepath=\"");



#line 25 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                                                                   WebViewPage.WriteTo(@__razor_helper_writer, obj.Path());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></a>\r\n");



#line 26 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionsLink(IObjectMethod method) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 28 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                                
#line default
#line hidden


#line 28 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
     WebViewPage.WriteTo(@__razor_helper_writer, NodeActionsLink(method, null));

#line default
#line hidden


#line 28 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                                                              
#line default
#line hidden

});

                                                                              }


public static System.Web.WebPages.HelperResult NodeActionsLink(IObjectMethod method, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 30 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <a class=\"nodeActionsLink ");



#line 31 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"#action-");



#line 31 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                 WebViewPage.WriteTo(@__razor_helper_writer, method.Target.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodeid=\"");



#line 31 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                                                   WebViewPage.WriteTo(@__razor_helper_writer, method.Target.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodepath=\"");



#line 31 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                                                                                       WebViewPage.WriteTo(@__razor_helper_writer, method.Target.Path());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-actionname=\"");



#line 31 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                                                                                                                               WebViewPage.WriteTo(@__razor_helper_writer, method.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 31 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"
                                                                                                                                                             WebViewPage.WriteTo(@__razor_helper_writer, method.DisplayName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 32 "..\..\Views\Shared\WebNoodle\Helpers.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
