#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoodle.Views.Shared.WebNoodle
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 4 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
    using WebNoodle;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/WebNoodle/NodeActions.cshtml")]
    public class NodeActions : System.Web.Mvc.WebViewPage<INode>
    {
        public NodeActions()
        {
        }
        public override void Execute()
        {





WriteLiteral(" \r\n");


            
            #line 7 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
 if (Model.NodeMethods().Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <div id=\"actions-");


            
            #line 9 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
                Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <ul>\r\n");


            
            #line 11 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
             foreach (var action in Model.NodeMethods())
            {

            
            #line default
            #line hidden
WriteLiteral("                <li style=\"display: block;\"><a class=\"nodeActionsPanelLink\" id=\"");


            
            #line 13 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
                                                                            Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("__");


            
            #line 13 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
                                                                                         Write(action.Name);

            
            #line default
            #line hidden
WriteLiteral("_actionlink\">");


            
            #line 13 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
                                                                                                                   Write(action.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a> </li>\r\n");


            
            #line 14 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </div>\r\n");


            
            #line 17 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"

            foreach (var command in Model.NodeMethods())
            {

            
            #line default
            #line hidden
WriteLiteral("    <div id=\"");


            
            #line 20 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
         Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("__");


            
            #line 20 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
                      Write(command.Name);

            
            #line default
            #line hidden
WriteLiteral("_actionlinkpanel\" class=\"modal hide fade\"   >\r\n        <form action=\"");


            
            #line 21 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
                 Write(Model.Path);

            
            #line default
            #line hidden
WriteLiteral("?action=");


            
            #line 21 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
                                    Write(command.Name);

            
            #line default
            #line hidden
WriteLiteral("\" method=\"post\" enctype=\"multipart/form-data\" encoding=\"multipart/form-data\">\r\n  " +
"      <div class=\"modal-header\">\r\n            <a href=\"#\" class=\"close\">×</a>\r\n " +
"           <h3>");


            
            #line 24 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
           Write(command.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n        </div>\r\n        <div class=\"modal-body\">\r\n");


            
            #line 27 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
             foreach (var parameter in command.Parameters)
            {
                var vm = new PropertyVm(Html, parameter.ParameterType, Model.Id + "_" + command.Name + "_" + parameter.Name, parameter.DisplayName)
                {
                    GetCustomAttributes = () => new Attribute[] { },
                    IsWritable = true,
                    Value = parameter.Value,
                    Choices = parameter.Choices,
                    Suggestions = parameter.Suggestions
                    
                };
                if (vm.Choices != null && vm.Choices.Cast<object>().Any() == false) {continue;} //no point rendering if there are no choices
                
                Html.RenderPartial("FormFactory/Form.Property", vm);

            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div class=\"modal-footer\">\r\n            <input type=\"subm" +
"it\" class=\"btn primary\" value=\"");


            
            #line 45 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
                                                       Write(command.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        </div>\r\n        </form>\r\n    </div>\r\n");



WriteLiteral("    <script type=\"text/javascript\">\r\n//        $(\'#");


            
            #line 50 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
          Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("__");


            
            #line 50 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
                       Write(command.Name);

            
            #line default
            #line hidden
WriteLiteral("_panel\').modal({ keyboard: true, backdrop: true })\r\n    </script>\r\n");


            
            #line 52 "..\..\Views\Shared\WebNoodle\NodeActions.cshtml"
            }
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
