#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoodle.Views.Shared.WebNoodle
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 4 "..\..\Views\Shared\WebNoodle\NodeAction.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\Shared\WebNoodle\NodeAction.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\WebNoodle\NodeAction.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\WebNoodle\NodeAction.cshtml"
    using WebNoodle;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/WebNoodle/NodeAction.cshtml")]
    public class NodeAction : System.Web.Mvc.WebViewPage<WebNoodle.Reflection.IObjectMethod>
    {
        public NodeAction()
        {
        }
        public override void Execute()
        {





WriteLiteral("<a class=\"nodeActionsPanelLink\" id=\"");


            
            #line 6 "..\..\Views\Shared\WebNoodle\NodeAction.cshtml"
                                Write(Model.Id());

            
            #line default
            #line hidden
WriteLiteral("_actionlink\">");


            
            #line 6 "..\..\Views\Shared\WebNoodle\NodeAction.cshtml"
                                                         Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n<div id=\"");


            
            #line 7 "..\..\Views\Shared\WebNoodle\NodeAction.cshtml"
     Write(Model.Id());

            
            #line default
            #line hidden
WriteLiteral("_actionlinkpanel\" class=\"modal hide fade\"   >\r\n    ");


            
            #line 8 "..\..\Views\Shared\WebNoodle\NodeAction.cshtml"
Write(Html.Partial("WebNoodle/NodeActionForm", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
