#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoodle.Example.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\Home\Home.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Home\Home.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Home.cshtml")]
    public class Home : System.Web.Mvc.WebViewPage<object>
    {
        public Home()
        {
        }
        public override void Execute()
        {



WriteLiteral("<div class=\"row\">\r\n    <div class=\"span4\">");


            
            #line 5 "..\..\Views\Home\Home.cshtml"
                  Write(Html.Partial("WebNoodle/NodeActions", Model));

            
            #line default
            #line hidden
WriteLiteral("&nbsp;</div>\r\n    <div class=\"span12\">\r\n");


            
            #line 7 "..\..\Views\Home\Home.cshtml"
           Html.RenderPropertiesFor(Model); 

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");


            
            #line 10 "..\..\Views\Home\Home.cshtml"
Write(Html.Partial("WebNoodle/NodeActionsLinkScript"));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
