#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noodles.Web.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 3 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    public static class NoodlesHelper
    {

public static System.Web.WebPages.HelperResult NodeActionsDropdown(object obj)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Helpers\NoodlesHelper.cshtml"
      
#line default
#line hidden


#line 7 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeActionsDropdown(obj, null));

#line default
#line hidden


#line 7 "..\..\Helpers\NoodlesHelper.cshtml"
                                      
#line default
#line hidden

});

                                      }


public static System.Web.WebPages.HelperResult NodeActionsDropdown(object obj, string additionalClasses)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 9 "..\..\Helpers\NoodlesHelper.cshtml"
     
    if (obj.NodeActions().Any())
    {
    
#line default
#line hidden


#line 12 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BootstrapHelper.DropdownLinksButton("Actions",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\n");



#line 14 "..\..\Helpers\NoodlesHelper.cshtml"
     foreach (var action in obj.NodeActions())
    {
        
#line default
#line hidden


#line 16 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_template_writer, NodeActionLink(action));

#line default
#line hidden


#line 16 "..\..\Helpers\NoodlesHelper.cshtml"
                               
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "    ");



#line 18 "..\..\Helpers\NoodlesHelper.cshtml"
         }), additionalClasses));

#line default
#line hidden


#line 18 "..\..\Helpers\NoodlesHelper.cshtml"
                               
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionsMenuLink(object obj)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 22 "..\..\Helpers\NoodlesHelper.cshtml"
      
#line default
#line hidden


#line 22 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeActionsMenuLink(obj, null));

#line default
#line hidden


#line 22 "..\..\Helpers\NoodlesHelper.cshtml"
                                      
#line default
#line hidden

});

                                      }


public static System.Web.WebPages.HelperResult NodeActionsMenuLink(object obj, string additionalClasses)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 24 "..\..\Helpers\NoodlesHelper.cshtml"
     
    if (obj.NodeActions().Any())
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"nodeActionsMenuLink ");



#line 27 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"#show actions\" data-nodeid=\"");



#line 27 "..\..\Helpers\NoodlesHelper.cshtml"
                                                     WebViewPage.WriteTo(@__razor_helper_writer, obj.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodeactionspath=\"");



#line 27 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                      WebViewPage.WriteTo(@__razor_helper_writer, obj.Path());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "?action=getNodeActions\">Actions</a>\n");



#line 28 "..\..\Helpers\NoodlesHelper.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionLink(INodeAction action)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 31 "..\..\Helpers\NoodlesHelper.cshtml"
      
#line default
#line hidden


#line 31 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeActionLink(action, null));

#line default
#line hidden


#line 31 "..\..\Helpers\NoodlesHelper.cshtml"
                                   
#line default
#line hidden

});

                                   }


public static System.Web.WebPages.HelperResult NodeActionLink(INodeAction action, string additionalClasses)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 33 "..\..\Helpers\NoodlesHelper.cshtml"
     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"nodeActionLink ");



#line 34 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"#");



#line 34 "..\..\Helpers\NoodlesHelper.cshtml"
                     WebViewPage.WriteTo(@__razor_helper_writer, action.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodeid=\"");



#line 34 "..\..\Helpers\NoodlesHelper.cshtml"
                                                WebViewPage.WriteTo(@__razor_helper_writer, action.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodepath=\"");



#line 34 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                             WebViewPage.WriteTo(@__razor_helper_writer, action.Path());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 34 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                             WebViewPage.WriteTo(@__razor_helper_writer, action.DisplayName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\n");



#line 35 "..\..\Helpers\NoodlesHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionForm(System.Web.Mvc.HtmlHelper html, INodeAction action, string formClass)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 37 "..\..\Helpers\NoodlesHelper.cshtml"
     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"objectAction\">\n        ");



#line 39 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Partial("Noodles/NodeAction", action, new ViewDataDictionary { { "FormClass", formClass ?? "" } }));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\n    </div>\n");



#line 41 "..\..\Helpers\NoodlesHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionForm(System.Web.Mvc.HtmlHelper html, INodeAction action, string formClass, ViewDataDictionary dict)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 43 "..\..\Helpers\NoodlesHelper.cshtml"
     
    dict = dict ?? new ViewDataDictionary();
    dict["FormClass"] = formClass;
    
#line default
#line hidden


#line 46 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeActionForm(html, action, dict));

#line default
#line hidden


#line 46 "..\..\Helpers\NoodlesHelper.cshtml"
                                       

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionForm(System.Web.Mvc.HtmlHelper html, INodeAction action, ViewDataDictionary dict)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 49 "..\..\Helpers\NoodlesHelper.cshtml"
     
    dict = dict ?? new ViewDataDictionary();

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"objectAction\">\n        ");



#line 52 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Partial("Noodles/NodeAction", action, dict));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\n    </div>\n");



#line 54 "..\..\Helpers\NoodlesHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionFormInline(System.Web.Mvc.HtmlHelper html, INodeAction action)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 56 "..\..\Helpers\NoodlesHelper.cshtml"
     
    
#line default
#line hidden


#line 57 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeActionFormInline(html, action, new ViewDataDictionary()));

#line default
#line hidden


#line 57 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeActionFormInline(System.Web.Mvc.HtmlHelper html, INodeAction action, ViewDataDictionary viewData)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 60 "..\..\Helpers\NoodlesHelper.cshtml"
     
    viewData = viewData ?? new ViewDataDictionary();
    viewData.Add("Inline", true);
    
#line default
#line hidden


#line 63 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeActionForm(html, action, "form-inline", viewData));

#line default
#line hidden


#line 63 "..\..\Helpers\NoodlesHelper.cshtml"
                                                          

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
