#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noodles.Web.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 3 "..\..\Helpers\NoodlesHelper.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Helpers\NoodlesHelper.cshtml"
    using Noodles.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    public static class NoodlesHelper
    {

public static System.Web.WebPages.HelperResult NodeMethodsDropdown(object obj)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Helpers\NoodlesHelper.cshtml"
      
#line default
#line hidden


#line 7 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodsDropdown(obj, null));

#line default
#line hidden


#line 7 "..\..\Helpers\NoodlesHelper.cshtml"
                                      
#line default
#line hidden

});

                                      }


public static System.Web.WebPages.HelperResult NodeMethodsDropdown(object obj, string additionalClasses)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 9 "..\..\Helpers\NoodlesHelper.cshtml"
      
#line default
#line hidden


#line 9 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodsDropdown(obj, null, null));

#line default
#line hidden


#line 9 "..\..\Helpers\NoodlesHelper.cshtml"
                                            
#line default
#line hidden

});

                                            }


public static System.Web.WebPages.HelperResult NodeMethodsDropdown(object obj, string additionalClasses, string excludedMethodNamesCsv)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 11 "..\..\Helpers\NoodlesHelper.cshtml"
     
        var excludedMethodNames = (excludedMethodNamesCsv ?? "").Split(',');
        var filteredNodeMethods = obj.NodeMethods().Where(nm => excludedMethodNames.Contains(nm.Name) == false);
        if (filteredNodeMethods.Any())
        {
    
#line default
#line hidden


#line 16 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BootstrapHelper.DropdownLinksButton("Actions",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\r\n");



#line 18 "..\..\Helpers\NoodlesHelper.cshtml"
     foreach (var method in filteredNodeMethods)
    {
        
#line default
#line hidden


#line 20 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_template_writer, NodeMethodLink(method));

#line default
#line hidden


#line 20 "..\..\Helpers\NoodlesHelper.cshtml"
                               
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "    ");



#line 22 "..\..\Helpers\NoodlesHelper.cshtml"
         }), additionalClasses));

#line default
#line hidden


#line 22 "..\..\Helpers\NoodlesHelper.cshtml"
                               
        }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodsMenuLink(object obj)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 26 "..\..\Helpers\NoodlesHelper.cshtml"
      
#line default
#line hidden


#line 26 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodsMenuLink(obj, null));

#line default
#line hidden


#line 26 "..\..\Helpers\NoodlesHelper.cshtml"
                                      
#line default
#line hidden

});

                                      }


public static System.Web.WebPages.HelperResult NodeMethodsMenuLink(object obj, string additionalClasses)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 28 "..\..\Helpers\NoodlesHelper.cshtml"
      
#line default
#line hidden


#line 28 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodsMenuLink(obj, additionalClasses, null));

#line default
#line hidden


#line 28 "..\..\Helpers\NoodlesHelper.cshtml"
                                                         
#line default
#line hidden

});

                                                         }


public static System.Web.WebPages.HelperResult NodeMethodsMenuLink(object obj, string additionalClasses, string excludedMethodNamesCsv)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 30 "..\..\Helpers\NoodlesHelper.cshtml"
     
        var excludedMethodNames = (excludedMethodNamesCsv ?? "").Split(',');
        var nodeMethods = obj.NodeMethods();
        if (nodeMethods.Any(nm => excludedMethodNames.Contains(nm.Name) == false))
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"nodeMethodsMenuLink ");



#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"");



#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
                         WebViewPage.WriteTo(@__razor_helper_writer, nodeMethods.Path());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodeid=\"");



#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
                                                           WebViewPage.WriteTo(@__razor_helper_writer, obj.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-excluded-methods=\"");



#line 35 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                             WebViewPage.WriteTo(@__razor_helper_writer, excludedMethodNamesCsv);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n        Actions</a>\r\n");



#line 37 "..\..\Helpers\NoodlesHelper.cshtml"
        }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodLink(INodeMethod method)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 40 "..\..\Helpers\NoodlesHelper.cshtml"
      
#line default
#line hidden


#line 40 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodLink(method, null));

#line default
#line hidden


#line 40 "..\..\Helpers\NoodlesHelper.cshtml"
                                   
#line default
#line hidden

});

                                   }


public static System.Web.WebPages.HelperResult NodeMethodLink(INodeMethod method, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 42 "..\..\Helpers\NoodlesHelper.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"nodeMethodLink ");



#line 43 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 43 "..\..\Helpers\NoodlesHelper.cshtml"
              WebViewPage.WriteTo(@__razor_helper_writer, method.Target.NodeType().Name.ToLowerInvariant());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "-");



#line 43 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                  WebViewPage.WriteTo(@__razor_helper_writer, method.Name.ToLowerInvariant());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodeid=\"");



#line 43 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                                 WebViewPage.WriteTo(@__razor_helper_writer, method.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"");



#line 43 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                                                     WebViewPage.WriteTo(@__razor_helper_writer, method.Path());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 43 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                                                                                                     WebViewPage.WriteTo(@__razor_helper_writer, method.DisplayName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 44 "..\..\Helpers\NoodlesHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodForm(System.Web.Mvc.HtmlHelper html, INodeMethod method, string formClass)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 46 "..\..\Helpers\NoodlesHelper.cshtml"
     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"nodeMethod\">\r\n        ");



#line 48 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Partial("Noodles/NodeMethod", method, new ViewDataDictionary { { "FormClass", formClass ?? "" } }));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    </div>\r\n");



#line 50 "..\..\Helpers\NoodlesHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodForm(System.Web.Mvc.HtmlHelper html, INodeMethod method, string formClass, ViewDataDictionary dict)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 52 "..\..\Helpers\NoodlesHelper.cshtml"
     
        dict = dict ?? new ViewDataDictionary();
        dict["FormClass"] = formClass;
    
#line default
#line hidden


#line 55 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodForm(html, method, dict));

#line default
#line hidden


#line 55 "..\..\Helpers\NoodlesHelper.cshtml"
                                       

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodForm(System.Web.Mvc.HtmlHelper html, INodeMethod method, ViewDataDictionary dict)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 58 "..\..\Helpers\NoodlesHelper.cshtml"
     
        dict = dict ?? new ViewDataDictionary();

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"nodeMethod\">\r\n        ");



#line 61 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Partial("Noodles/NodeMethod", method, dict));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    </div>\r\n");



#line 63 "..\..\Helpers\NoodlesHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodFormInline(System.Web.Mvc.HtmlHelper html, INodeMethod method)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 65 "..\..\Helpers\NoodlesHelper.cshtml"
     
    
#line default
#line hidden


#line 66 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodFormInline(html, method, new ViewDataDictionary()));

#line default
#line hidden


#line 66 "..\..\Helpers\NoodlesHelper.cshtml"
                                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodFormInline(System.Web.Mvc.HtmlHelper html, INodeMethod method, ViewDataDictionary viewData)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 69 "..\..\Helpers\NoodlesHelper.cshtml"
     
        viewData = viewData ?? new ViewDataDictionary();
        viewData.Add("Inline", true);
    
#line default
#line hidden


#line 72 "..\..\Helpers\NoodlesHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodForm(html, method, "form-inline", viewData));

#line default
#line hidden


#line 72 "..\..\Helpers\NoodlesHelper.cshtml"
                                                          

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
