#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoodle.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\Helpers\Bootstrap.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    public static class Bootstrap
    {

public static System.Web.WebPages.HelperResult DropdownLinksButton(string buttonTitle, Func<MvcHtmlString, HelperResult> links)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 4 "..\..\Helpers\Bootstrap.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"btn-group\">\r\n        <a class=\"btn dropdown-toggle\" data-toggle=\"" +
"dropdown\" href=\"#\">");



#line 6 "..\..\Helpers\Bootstrap.cshtml"
                            WebViewPage.WriteTo(@__razor_helper_writer, buttonTitle);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <span class=\"caret\"></span></a>\r\n        <ul class=\"dropdown-menu\">\r\n           " +
" ");



#line 8 "..\..\Helpers\Bootstrap.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, links(null));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        </ul>\r\n    </div>\r\n");



#line 11 "..\..\Helpers\Bootstrap.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
