#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoodle.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Helpers\Noodles.cshtml"
    using WebNoodle;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Helpers\Noodles.cshtml"
    using WebNoodle.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    public static class Noodles
    {

public static System.Web.WebPages.HelperResult NodeActionsDropdown(object obj, string additionalClasses = null)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 5 "..\..\Helpers\Noodles.cshtml"
 
    if (obj.NodeMethods().Any())
    {
    
#line default
#line hidden


#line 8 "..\..\Helpers\Noodles.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Bootstrap.DropdownLinksButton("Actions",item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\r\n");



#line 9 "..\..\Helpers\Noodles.cshtml"
     foreach (var method in obj.NodeMethods())
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "        <a class=\"nodeActionsLink ");



#line 11 "..\..\Helpers\Noodles.cshtml"
WebViewPage.WriteTo(@__razor_template_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\" href=\"#action-");



#line 11 "..\..\Helpers\Noodles.cshtml"
                               WebViewPage.WriteTo(@__razor_template_writer, obj.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\" data-nodeid=\"");



#line 11 "..\..\Helpers\Noodles.cshtml"
                                                       WebViewPage.WriteTo(@__razor_template_writer, obj.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\" data-nodepath=\"");



#line 11 "..\..\Helpers\Noodles.cshtml"
                                                                                 WebViewPage.WriteTo(@__razor_template_writer, obj.Path());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\" data-actionname=\"");



#line 11 "..\..\Helpers\Noodles.cshtml"
                                                                                                               WebViewPage.WriteTo(@__razor_template_writer, method.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\">(edit)</a>\r\n");



#line 12 "..\..\Helpers\Noodles.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "    ");



#line 13 "..\..\Helpers\Noodles.cshtml"
         })));

#line default
#line hidden


#line 13 "..\..\Helpers\Noodles.cshtml"
            
    }
    

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
