#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoodle.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Helpers\Noodles.cshtml"
    using WebNoodle;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Helpers\Noodles.cshtml"
    using WebNoodle.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    public static class Noodles
    {

public static System.Web.WebPages.HelperResult NodeActionsDropdown(object obj) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 5 "..\..\Helpers\Noodles.cshtml"
                                          
#line default
#line hidden


#line 5 "..\..\Helpers\Noodles.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeActionsDropdown(obj, null));

#line default
#line hidden


#line 5 "..\..\Helpers\Noodles.cshtml"
                                                                          
#line default
#line hidden

});

                                                                          }


public static System.Web.WebPages.HelperResult NodeActionsDropdown(object obj, string additionalClasses)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Helpers\Noodles.cshtml"
 
    if (obj.NodeMethods().Any())
    {
        
#line default
#line hidden


#line 10 "..\..\Helpers\Noodles.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Bootstrap.DropdownLinksButton("Actions",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\n");



#line 12 "..\..\Helpers\Noodles.cshtml"
                 foreach (var method in obj.NodeMethods())
                {
                    
#line default
#line hidden


#line 14 "..\..\Helpers\Noodles.cshtml"
WebViewPage.WriteTo(@__razor_template_writer, NodeMethodLink(method));

#line default
#line hidden


#line 14 "..\..\Helpers\Noodles.cshtml"
                                           
                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "            ");



#line 16 "..\..\Helpers\Noodles.cshtml"
                 })));

#line default
#line hidden


#line 16 "..\..\Helpers\Noodles.cshtml"
                    
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodsMenuLink(object obj) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 19 "..\..\Helpers\Noodles.cshtml"
                                          
#line default
#line hidden


#line 19 "..\..\Helpers\Noodles.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodsMenuLink(obj, null));

#line default
#line hidden


#line 19 "..\..\Helpers\Noodles.cshtml"
                                                                          
#line default
#line hidden

});

                                                                          }


public static System.Web.WebPages.HelperResult NodeMethodsMenuLink(object obj, string additionalClasses) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 20 "..\..\Helpers\Noodles.cshtml"
                                                                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"nodeMethodsMenuLink ");



#line 21 "..\..\Helpers\Noodles.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"#show actions\" data-nodeid=\"");



#line 21 "..\..\Helpers\Noodles.cshtml"
                                                     WebViewPage.WriteTo(@__razor_helper_writer, obj.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodemethodspath=\"");



#line 21 "..\..\Helpers\Noodles.cshtml"
                                                                                      WebViewPage.WriteTo(@__razor_helper_writer, obj.Path());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "?action=getNodeMethods\">Actions</a>\n");



#line 22 "..\..\Helpers\Noodles.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult NodeMethodLink(IObjectMethod method) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 23 "..\..\Helpers\Noodles.cshtml"
                                               
#line default
#line hidden


#line 23 "..\..\Helpers\Noodles.cshtml"
    WebViewPage.WriteTo(@__razor_helper_writer, NodeMethodLink(method, null));

#line default
#line hidden


#line 23 "..\..\Helpers\Noodles.cshtml"
                                                                            
#line default
#line hidden

});

                                                                            }


public static System.Web.WebPages.HelperResult NodeMethodLink(IObjectMethod method, string additionalClasses)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 25 "..\..\Helpers\Noodles.cshtml"
     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"nodeMethodLink ");



#line 26 "..\..\Helpers\Noodles.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, additionalClasses ?? "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"#");



#line 26 "..\..\Helpers\Noodles.cshtml"
                     WebViewPage.WriteTo(@__razor_helper_writer, method.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodeid=\"");



#line 26 "..\..\Helpers\Noodles.cshtml"
                                                WebViewPage.WriteTo(@__razor_helper_writer, method.Id());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-nodepath=\"");



#line 26 "..\..\Helpers\Noodles.cshtml"
                                                                             WebViewPage.WriteTo(@__razor_helper_writer, method.Path());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 26 "..\..\Helpers\Noodles.cshtml"
                                                                                             WebViewPage.WriteTo(@__razor_helper_writer, method.DisplayName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\n");



#line 27 "..\..\Helpers\Noodles.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
